# Generated by Django 3.2.4 on 2021-06-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0003_film_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='imdb_rating',
            field=models.CharField(max_length=64),
        ),
    ]
