# Generated by Django 3.1.4 on 2021-06-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0004_alter_film_imdb_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='plot',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
