# Generated by Django 3.1.4 on 2021-06-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0005_film_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='seats_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='film',
            name='seats_sold',
            field=models.IntegerField(default=0),
        ),
    ]
