# Generated by Django 3.1.4 on 2021-07-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0007_auto_20210701_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='reserved_seats',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seats',
            field=models.TextField(default=''),
        ),
    ]
