# Generated by Django 3.1.4 on 2021-07-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0009_auto_20210701_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='reserved_seats',
            field=models.TextField(null=True),
        ),
    ]
