# Generated by Django 3.1.4 on 2021-07-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0010_auto_20210701_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='seats_sold',
            new_name='reserved_seats_amount',
        ),
        migrations.AlterField(
            model_name='film',
            name='reserved_seats',
            field=models.TextField(blank=True, null=True),
        ),
    ]
