# Generated by Django 3.1.4 on 2021-07-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0011_auto_20210702_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='seats',
            new_name='seats_code',
        ),
        migrations.AddField(
            model_name='reservation',
            name='seats_number',
            field=models.TextField(default=''),
        ),
    ]
