# Generated by Django 3.1.4 on 2021-07-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0016_auto_20210704_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
