# Generated by Django 3.1.4 on 2021-07-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0017_film_date_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_reserved',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
