# Generated by Django 3.1.4 on 2021-07-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0018_reservation_date_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='reserved_seats',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
